<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-CK6VHMT" failures="18" tests="29" name="Test" time="28.732" errors="0" timestamp="2023-04-11T07:23:15 IST">
  <testcase classname="utility.DataExtractor" name="CreateCustomer" time="4.706"/>
  <testcase classname="utility.DataExtractor" name="CreateCustomer" time="0.673"/>
  <testcase classname="utility.DataExtractor" name="CreateCustomer" time="0.926"/>
  <testcase classname="utility.DataExtractor" name="CreateCustomer" time="0.904"/>
  <testcase classname="utility.DataExtractor" name="CreateCustomer" time="0.929"/>
  <testcase classname="utility.DataExtractor" name="CreateCustomer" time="0.648"/>
  <testcase classname="utility.DataExtractor" name="CreateCustomer" time="0.695"/>
  <testcase classname="utility.DataExtractor" name="CreateCustomer" time="0.743"/>
  <testcase classname="utility.DataExtractor" name="CreateCustomer" time="0.712"/>
  <testcase classname="testcases.CreateCustomerAPI" name="TC1_validAPIKeys" time="0.711">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [1000] but found [678]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [1000] but found [678]
at testcases.CreateCustomerAPI.TC1_validAPIKeys(CreateCustomerAPI.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- TC1_validAPIKeys -->
  <testcase classname="testcases.CreateCustomerAPI" name="TC1_validAPIKeys" time="0.768">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [1000] but found [755]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [1000] but found [755]
at testcases.CreateCustomerAPI.TC1_validAPIKeys(CreateCustomerAPI.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- TC1_validAPIKeys -->
  <testcase classname="testcases.CreateCustomerAPI" name="TC1_validAPIKeys" time="3.278">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [1000] but found [3264]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [1000] but found [3264]
at testcases.CreateCustomerAPI.TC1_validAPIKeys(CreateCustomerAPI.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- TC1_validAPIKeys -->
  <testcase classname="testcases.CreateCustomerAPI" name="TC1_validAPIKeys" time="1.314">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [1000] but found [1299]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [1000] but found [1299]
at testcases.CreateCustomerAPI.TC1_validAPIKeys(CreateCustomerAPI.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- TC1_validAPIKeys -->
  <testcase classname="testcases.CreateCustomerAPI" name="TC1_validAPIKeys" time="0.721">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [1000] but found [711]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [1000] but found [711]
at testcases.CreateCustomerAPI.TC1_validAPIKeys(CreateCustomerAPI.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- TC1_validAPIKeys -->
  <testcase classname="testcases.CreateCustomerAPI" name="TC1_validAPIKeys" time="0.692">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [1000] but found [681]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [1000] but found [681]
at testcases.CreateCustomerAPI.TC1_validAPIKeys(CreateCustomerAPI.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- TC1_validAPIKeys -->
  <testcase classname="testcases.CreateCustomerAPI" name="TC1_validAPIKeys" time="0.724">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [1000] but found [700]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [1000] but found [700]
at testcases.CreateCustomerAPI.TC1_validAPIKeys(CreateCustomerAPI.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- TC1_validAPIKeys -->
  <testcase classname="testcases.CreateCustomerAPI" name="TC1_validAPIKeys" time="0.869">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [1000] but found [858]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [1000] but found [858]
at testcases.CreateCustomerAPI.TC1_validAPIKeys(CreateCustomerAPI.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- TC1_validAPIKeys -->
  <testcase classname="testcases.CreateCustomerAPI" name="TC1_validAPIKeys" time="0.675">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [1000] but found [667]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [1000] but found [667]
at testcases.CreateCustomerAPI.TC1_validAPIKeys(CreateCustomerAPI.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- TC1_validAPIKeys -->
  <testcase classname="testcases.CreateCustomerAPI" name="TC2_skipTestcase" time="0.0">
    <skipped/>
  </testcase> <!-- TC2_skipTestcase -->
  <testcase classname="testcases.GetCustomerAPI" name="TC1_validAPIKey" time="2.002">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [400] but found [200],
	expected [HTTP/1.1 400 OK] but found [HTTP/1.1 200 OK],
	expected [1000] but found [502]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [400] but found [200],
expected [HTTP/1.1 400 OK] but found [HTTP/1.1 200 OK],
expected [1000] but found [502]
at testcases.GetCustomerAPI.TC1_validAPIKey(GetCustomerAPI.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- TC1_validAPIKey -->
  <testcase classname="testcases.GetCustomerAPI" name="TC1_validAPIKey" time="0.487">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [400] but found [200],
	expected [HTTP/1.1 400 OK] but found [HTTP/1.1 200 OK],
	expected [vaibhav@testing.com] but found [john@testing.com],
	expected [1000] but found [435]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [400] but found [200],
expected [HTTP/1.1 400 OK] but found [HTTP/1.1 200 OK],
expected [vaibhav@testing.com] but found [john@testing.com],
expected [1000] but found [435]
at testcases.GetCustomerAPI.TC1_validAPIKey(GetCustomerAPI.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- TC1_validAPIKey -->
  <testcase classname="testcases.GetCustomerAPI" name="TC1_validAPIKey" time="0.491">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [400] but found [200],
	expected [HTTP/1.1 400 OK] but found [HTTP/1.1 200 OK],
	expected [vaibhav@testing.com] but found [john@testing.com],
	expected [1000] but found [454]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [400] but found [200],
expected [HTTP/1.1 400 OK] but found [HTTP/1.1 200 OK],
expected [vaibhav@testing.com] but found [john@testing.com],
expected [1000] but found [454]
at testcases.GetCustomerAPI.TC1_validAPIKey(GetCustomerAPI.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- TC1_validAPIKey -->
  <testcase classname="testcases.GetCustomerAPI" name="TC1_validAPIKey" time="0.525">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [400] but found [200],
	expected [HTTP/1.1 400 OK] but found [HTTP/1.1 200 OK],
	expected [vaibhav@testing.com] but found [john@testing.com],
	expected [1000] but found [488]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [400] but found [200],
expected [HTTP/1.1 400 OK] but found [HTTP/1.1 200 OK],
expected [vaibhav@testing.com] but found [john@testing.com],
expected [1000] but found [488]
at testcases.GetCustomerAPI.TC1_validAPIKey(GetCustomerAPI.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- TC1_validAPIKey -->
  <testcase classname="testcases.GetCustomerAPI" name="TC1_validAPIKey" time="0.425">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [400] but found [200],
	expected [HTTP/1.1 400 OK] but found [HTTP/1.1 200 OK],
	expected [vaibhav@testing.com] but found [john@testing.com],
	expected [1000] but found [390]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [400] but found [200],
expected [HTTP/1.1 400 OK] but found [HTTP/1.1 200 OK],
expected [vaibhav@testing.com] but found [john@testing.com],
expected [1000] but found [390]
at testcases.GetCustomerAPI.TC1_validAPIKey(GetCustomerAPI.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- TC1_validAPIKey -->
  <testcase classname="testcases.GetCustomerAPI" name="TC1_validAPIKey" time="0.503">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [400] but found [200],
	expected [HTTP/1.1 400 OK] but found [HTTP/1.1 200 OK],
	expected [vaibhav@testing.com] but found [john@testing.com],
	expected [1000] but found [467]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [400] but found [200],
expected [HTTP/1.1 400 OK] but found [HTTP/1.1 200 OK],
expected [vaibhav@testing.com] but found [john@testing.com],
expected [1000] but found [467]
at testcases.GetCustomerAPI.TC1_validAPIKey(GetCustomerAPI.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- TC1_validAPIKey -->
  <testcase classname="testcases.GetCustomerAPI" name="TC1_validAPIKey" time="0.439">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [400] but found [200],
	expected [HTTP/1.1 400 OK] but found [HTTP/1.1 200 OK],
	expected [vaibhav@testing.com] but found [john@testing.com],
	expected [1000] but found [407]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [400] but found [200],
expected [HTTP/1.1 400 OK] but found [HTTP/1.1 200 OK],
expected [vaibhav@testing.com] but found [john@testing.com],
expected [1000] but found [407]
at testcases.GetCustomerAPI.TC1_validAPIKey(GetCustomerAPI.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- TC1_validAPIKey -->
  <testcase classname="testcases.GetCustomerAPI" name="TC1_validAPIKey" time="0.567">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [400] but found [200],
	expected [HTTP/1.1 400 OK] but found [HTTP/1.1 200 OK],
	expected [vaibhav@testing.com] but found [john@testing.com],
	expected [1000] but found [536]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [400] but found [200],
expected [HTTP/1.1 400 OK] but found [HTTP/1.1 200 OK],
expected [vaibhav@testing.com] but found [john@testing.com],
expected [1000] but found [536]
at testcases.GetCustomerAPI.TC1_validAPIKey(GetCustomerAPI.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- TC1_validAPIKey -->
  <testcase classname="testcases.GetCustomerAPI" name="TC1_validAPIKey" time="0.507">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [400] but found [200],
	expected [HTTP/1.1 400 OK] but found [HTTP/1.1 200 OK],
	expected [vaibhav@testing.com] but found [john@testing.com],
	expected [1000] but found [475]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [400] but found [200],
expected [HTTP/1.1 400 OK] but found [HTTP/1.1 200 OK],
expected [vaibhav@testing.com] but found [john@testing.com],
expected [1000] but found [475]
at testcases.GetCustomerAPI.TC1_validAPIKey(GetCustomerAPI.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- TC1_validAPIKey -->
  <testcase classname="testcases.GetCustomerAPI" name="TC2_invalidAPIKey" time="0.33"/>
</testsuite> <!-- Test -->
